site_name: "ParseDMARC"
site_url: https://nhairs.github.io/parsedmarc
repo_url: https://github.com/nhairs/parsedmarc
edit_uri: tree/docs/docs
copyright: "Copyright &copy; Parsedmarc Contributors</a>"
watch:
  - mkdocs.yml
  - README.md
  - src
  - docs

nav:
  - "Home": index.md
  - installation.md
  - usage.md
  - output.md
  - elasticsearch.md
  - kibana.md
  - splunk.md
  - davmail.md
  - contributing.md
  # - changelog.md
  - DMARC:
    - dmarc.md
    - mailing-lists.md
  - API Reference:
    - ... | reference/parsedmarc/*

theme:
  name: material

  icon:
    logo: material/email

  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nhairs/parsedmarc
  version:
    provider: mike

markdown_extensions:
  - toc:
      permalink: "ðŸ”—"
  - admonition
  - tables
  - def_list
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret

plugins:
  - autorefs
  - search:
      lang: en
  - awesome-pages:
      collapse_single_pages: true
  - gen-files:
      scripts:
        - scripts/gen_ref_nav.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          #import:
          #  - https://docs.python.org/3/objects.inv
          #  - https://mkdocstrings.github.io/objects.inv
          #  - https://mkdocstrings.github.io/griffe/objects.inv
          options:
            filters:
              - "!^_"
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            #preload_modules: []
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true
            show_source: false
  - literate-nav:
      nav_file: SUMMARY.txt
  - mike:
      canonical_version: latest


